query StarHistory(
    $owner: String!
    $name: String!
    $after: String
    $before: String
    $first: Int
    $last: Int
) {
    repository(owner: $owner, name: $name) {
        stargazerCount
        stargazers(first: $first, after: $after, last: $last, before: $before) {
            edges {
                starredAt
            }
            totalCount
            pageInfo {
                endCursor
                hasNextPage
                hasPreviousPage
                startCursor
            }
        }
    }
}
