/**
 * This test file tests the graphql-request SDK generated by the `graphql-codegen` plugin.
 */
import { expect, test } from "bun:test"
import { GraphQLClient } from "graphql-request"
import { getSdk } from "../src/generated/req"

const client = new GraphQLClient("https://api.github.com/graphql", {
	headers: {
		authorization: `Bearer ${Bun.env.GITHUB_TOKEN}`,
		"User-Agent": "github-graphql package"
	}
})
const sdk = getSdk(client)

test("Get repo info", async () => {
	const data = await sdk.Repository({
		owner: "tauri-apps",
		name: "tauri"
	})

	expect(data.data.repository?.stargazerCount).toBeGreaterThan(100)
})

test("Get Rate Limit Info", async () => {
	const data = await sdk.RateLimit()
	expect(data.data.rateLimit).toBeDefined()
	const { limit, remaining, used, resetAt } = data.data.rateLimit!
	expect(limit).toBeDefined()
	expect(remaining).toBeDefined()
	expect(used).toBeDefined()
	expect(new Date(resetAt)).toBeDefined()
})

test("Get User Contribution", async () => {
	const defaultContribution = await sdk.DefaultGitHubContribution({
		username: "HuakunShen"
	})
	const contributionCollection = defaultContribution.data.user?.contributionsCollection
	expect(contributionCollection?.contributionCalendar.weeks.length).toBe(53)
})

test("Get User Contribution By Date", async () => {
	const startDate = new Date("2021-01-01")
	const endDate = new Date("2021-12-31")
	const defaultContribution = await sdk.GitHubContributionByDate({
		username: "HuakunShen",
		from: startDate.toISOString(),
		to: endDate.toISOString()
	})
	const contributionCollection = defaultContribution.data.user?.contributionsCollection
	console.log(contributionCollection?.contributionCalendar.weeks.length)
	expect(contributionCollection?.contributionCalendar.weeks.length).toBe(53)
})
